### ISSUE TITLE
When p360 is run, attr library is missing

### ISSUE THREAD

**Issue by ChameleonTartu** [greenbird/p360-contact-manager#47]
> p360 -ak <auth_key> -pbu <public_url> test
Traceback (most recent call last):
  File "/Users/dmitry/.pyenv/versions/3.8.5/bin/p360", line 5, in <module>
    from p360_contact_manager.cli import main
  File "/Users/dmitry/.pyenv/versions/3.8.5/lib/python3.8/site-packages/p360_contact_manager/cli.py", line 10, in <module>
    from p360_contact_manager.api import p360
  File "/Users/dmitry/.pyenv/versions/3.8.5/lib/python3.8/site-packages/p360_contact_manager/api/p360.py", line 9, in <module>
    from attr import dataclass
ImportError: cannot import name 'dataclass' from 'attr' (/Users/dmitry/.pyenv/versions/3.8.5/lib/python3.8/site-packages/attr.py)

**Comment by thomasborgen** [comment]
Oh wow, it seems attrs was not added to dependencies. 
Sry about that.
